#!/bin/bash

# Set up environment variables for petalinux

# Workspace of PetaLinux
export WORKSPACE_PATH=/scratch/vogelpi/te0808/petalinux/TEBF0808

# Path to prebuilt images
export PREBUILT_PATH=${WORKSPACE_PATH}/prebuilt/os/petalinux/default

# Path to bitstream
export BITSTREAM_PATH=${WORKSPACE_PATH}/os/wimmis02/images/linux

# Path to images generated by PetaLinux
export IMAGE_PATH=${WORKSPACE_PATH}/os/wimmis02/images/linux