#!/bin/bash

# Set up environment variables for petalinux

export TARGET_NAME=wimmis02

# Workspace of PetaLinux
export WORKSPACE_PATH=/scratch/vogelpi/te0808/petalinux/TEBF0808

# Path to target system
export TARGET_PATH=${WORKSPACE_PATH}/os/${TARGET_NAME}

# Path to prebuilt images
export PREBUILT_PATH=${WORKSPACE_PATH}/prebuilt

# Path to bitstream
export BITSTREAM_PATH=${TARGET_PATH}/images/linux

# Path to images generated by PetaLinux
export IMAGE_PATH=${TARGET_PATH}/images/linux