#! /bin/bash
# Copyright (C) 2018 ETH Zurich and University of Bologna
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Error handler
# set -e
trap 'previous_command=$this_command; this_command=$BASH_COMMAND' DEBUG
trap 'echo FAILED COMMAND: $previous_command' ERR

if [[ ! -f "${0##*/}" ]]; then
    echo "Error: ${0##*/} should be launched from the directory that contains it"
    exit 1
fi

# Usage info
show_help() {
cat << EOF
Usage: ${0##*/} [-hdlt]
HERO software builder:
    -h    : display this help and exit
    -d    : DOWNLOAD external software dependency
    -l    : build WHOLE Linux Environment
    -t    : bulld WHOLE GNU GCC Toolchain
EOF
}

# Global variables
source platforms/hero-zc706-env.sh
PARBUILD=-j12
GET_SOURCES=false
BUILD_LINUX=false
BUILD_TOOLCHAIN=false

while getopts hdlt opt; do
    case $opt in
        d)
            GET_SOURCES=true
            ;;
        l)
            BUILD_LINUX=true
            ;;
        t)
            BUILD_TOOLCHAIN=true
            ;;
        h)
            show_help
            exit 0
            ;;
        *)
            show_help >&2
            exit 1
            ;;
    esac
done

if [ "$GET_SOURCES" = true ] ; then
    source platforms/hero-zc706-get-src.sh
fi

if [ "$BUILD_LINUX" = true ] ; then
    cd ${HERO_SDK_DIR}/linux/zynqlinux
    ./linux_builder
fi

if [ "$BUILD_TOOLCHAIN" = true ] ; then
    cd ${HERO_SDK_DIR}/hero-gnu-gcc-toolchain
    ./hero_accel_builder -a
    ./hero_host_builder -a
fi

# That's all folks!!
